[package]
name = "pubky-sdk-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pubky = { path = "../pubky-sdk" }
tokio = { version = "1", features = ["full"] }
once_cell = "1.18.0"
libc = "0.2.140"
url = "2.3.1"
